name: dcss
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - graph-tool
  - mkl
  - pandas
  - leidenalg
  - seaborn
  - matplotlib
  - scikit-learn
  - spacy
  - spacy-lookups-data
  - pymc3
  - cairocffi
  - pip
  - numpy
  - pyldavis
  - transformers
  - pip:
    - beautifulsoup4
    - gensim
    - ndlib
    - networkx
    - graphviz
    - python-louvain
    - pyyaml
    - tensorflow
    - torch
    - dcss
    - lxml
